### ISSUE TITLE
Consider new organisation in project name

### ISSUE THREAD

**Issue by W0rma** [FriendsOfSymfony1/symfony1#226]
The name of this project is still `lexpress/symfony1` (see [`composer.json`](https://github.com/FriendsOfSymfony1/symfony1/blob/master/composer.json#L2). Should it be changed to `friendsofsymfony1/symfony1`?

It may need to be renamed in packagist, too.

**Comment by alquerci** [comment]
Already done for Doctrine1 but indeed not yet for symfony1.

related to https://github.com/FriendsOfSymfony1/doctrine1/pull/63
