### ISSUE TITLE
v1.5.13 not compatible with PHP 7.3

### ISSUE THREAD

**Issue by trebitzki** [FriendsOfSymfony1/symfony1#259]
In preparation for changing to PHP 7.4 I tested v1.5.13 with PHP 7.3. Got a white page on the website; the site works with v1.5.11. Has anyone had any similar issues? Also, is v1.5.13 fully compatible with 7.4?

**Comment by michilehr** [comment]
Did you check the error logs? Maybe it is an extension which is missing.

**Comment by trebitzki** [comment]
Does 1.5.13 need an extra extension? I didn't need one for 1.5.11. I'll check the logs and get back to you.

**Comment by trebitzki** [comment]
The vendor/swiftmailer content was missing. I copied it from 1.5.11, now it works. Thanks!

**Comment by e1himself** [comment]
> I copied it from 1.5.11, now it works

@trebitzki I really recommend starting using Composer and link swiftmailer as a composer dependency. It's the best way to move forward with any legacy project.
