### ISSUE TITLE
How to upgrade from 1.4.16

### ISSUE THREAD

**Issue by ceochronos** [FriendsOfSymfony1/symfony1#260]
Can you give me a general idea about how to start upgrading my app?

The app is actively used with dozens of models and modules. 

Is it possible to upgrade directly to 1.5.13 or Do I have to upgrade release by release?

I'm using Symfony 1.4.16 with propel

**Comment by ceochronos** [comment]
thanks, a good starting point. The composer tip will be useful

**Comment by gigo6000** [comment]
@alquerci yeah that seems like a more elegant solution I may try that next time, thanks.

This are not really steps but more like my notes but when I have a chance I will organize them better and create a PR. I've upgraded about 3 projects so far so I may have more notes somewhere.
