### ISSUE TITLE
Error on executing test

### ISSUE THREAD

**Issue by saracubillas** [FriendsOfSymfony1/symfony1#269]
Im getting this error on executing the test
+ docker-compose build
failed to solve: executor failed running [/bin/sh -c set -eux;     apt-get update;   apt-get install -y     curl     autoconf2.13   ;   rm -r /var/lib/apt/lists/*;     curl -sSLfO http://launchpadlibrarian.net/140087283/libbison-dev_2.7.1.dfsg-1_amd64.deb;   curl -sSLfO http://launchpadlibrarian.net/140087282/bison_2.7.1.dfsg-1_amd64.deb;   dpkg -i libbison-dev_2.7.1.dfsg-1_amd64.deb;   dpkg -i bison_2.7.1.dfsg-1_amd64.deb;   rm *.deb;     curl -sSLf "https://php.net/get/php-$PHP_VERSION.tar.bz2/from/this/mirror" -o php.tar.bz2;   echo 'c4e1cf6972b2a9c7f2777a18497d83bf713cdbecabb65d3ff62ba441aebb0091  php.tar.bz2' | sha256sum -cw --status;     mkdir -p /usr/src/php;   tar -xf php.tar.bz2 -C /usr/src/php --strip-components=1;   rm php.tar.bz2*;     cd /usr/src/php;   ./buildconf --force;   ./configure --disable-cgi     $(command -v apxs2 > /dev/null 2>&1 && echo '--with-apxs2' || true)     --with-pdo-mysql     --with-zlib     --enable-mbstring   ;   make -j"$(nproc)";   make install;     dpkg -r     bison     libbison-dev   ;   apt-get purge -y --auto-remove     autoconf2.13   ;   rm -r /usr/src/php]: exit code: 100

**Comment by alquerci** [comment]
@saracubillas Indeed nice cache.

Something change with new docker version.

I will provide a patch soon.

**Comment by mentalstring** [comment]
The use of Docker images should minimize the odds that something external to symfony changed so that everyone gets the same environment. Would it help here to set the Dockerfile to use a specific version of jessie?

**Comment by alquerci** [comment]
> Would it help here to set the Dockerfile to use a specific version of jessie?

I am going to add this restriction on the patch PR.

**Comment by alquerci** [comment]
Hum, no, the issue was about a gpg signature expiration.

```
W: GPG error: http://deb.debian.org jessie-updates InRelease: The following signatures were invalid: KEYEXPIRED 1668891673
W: GPG error: http://deb.debian.org jessie Release: The following signatures were invalid: KEYEXPIRED 1668891673
```
