### ISSUE TITLE
php-cs-fixer workflow

### ISSUE THREAD

**Issue by connorhu** [FriendsOfSymfony1/symfony1#276]
As we talked about it, we could make a github action to test php coding standards (later maybe code sniffer).

This is a tested config for push event:
https://github.com/FriendsOfSymfony1/doctrine1/compare/master...connorhu:doctrine1:feature/phpcsfixer
https://github.com/FriendsOfSymfony1/symfony1/compare/master...connorhu:symfony1:feature/phpcsfixer

I have to test it for PR event, but it works for push. When I have tested for PR I will make a pull request. The cs-fixer setting is left at minimum (only tests what @thePanz noticed to in my PR at https://github.com/FriendsOfSymfony1/doctrine1/pull/94 ).
It's another question of what the setting should be at all. @Symfony ruleset would be logical, but it's a very aggressive and generates a very different style from current code formatting.

We should only test the files we touch.

**Comment by thePanz** [comment]
Fixed in https://github.com/FriendsOfSymfony1/symfony1/pull/283
