### ISSUE TITLE
Add migration Instructions to Wiki

### ISSUE THREAD

**Issue by derflocki** [FriendsOfSymfony1/symfony1#278]
I'm currently updating one of my projects to this version of friendsofsymfony1/symfony1. Currently everything went pretty easy, so thanks for your great work! My plan is to migrate ~10 more legacy projects, with significantly more code.

If you want, I would start updating the Wiki with install and upgrade instructions.

**Comment by connorhu** [comment]
It would be great if you could write a proper summary of the migration process. That could close issues #260 and #244

**Comment by thirsch** [comment]
Sounds great, thank you! Maybe updating https://github.com/FriendsOfSymfony1/symfony1/blob/master/UPGRADE.md in a pr with any advices and hints?

**Comment by connorhu** [comment]
One of my projects needs to be migrated, I will do this issue.

**Comment by connorhu** [comment]
First draft
https://github.com/FriendsOfSymfony1/symfony1/wiki/Migrations

**Comment by alquerci** [comment]
@connorhu that's a good start.
