### ISSUE TITLE
swiftmailer directory empty

### ISSUE THREAD

**Issue by flmommens** [FriendsOfSymfony1/symfony1#289]
Hi,

Thanks for the effort in maintaining Symfony 1 !!

I've decided to migrate a big project.

These are the steps I have done so far:

- installing the symfony1 and doctrine1 packages with composer
- set `sf_doctrine_dir` in ProjectConfiguration.class.php to point to the correct directory and
-  added `require_once dirname(__FILE__).[project_root]/lib/vendor/friendsofsymfony1/symfony1/lib/autoload/sfCoreAutoload.class.php`

Now I've got an error with Swift Mailer:
`require_once([project_root]/lib/vendor/friendsofsymfony1/symfony1/lib/vendor/swiftmailer/lib/swift_required.php): failed to open stream`

The directory `[project_root]lib/vendor/friendsofsymfony1/symfony1/lib/vendor/swiftmailer` is actually empty.

Do I need to install this package and how? The documentation seems to indicate that symfony 1.5.x comes with Swift Mailer.

**Comment by mentalstring** [comment]
Just tried a `composer require friendsofsymfony1/symfony1` on a new project and it installed swiftmailer with it.

Did you override the default location for composer's `vendor` directory? Normally it should be in the root of the project, but it appears you have it at `lib/vendor`. Might be the clue for why you are having trouble. Try the default and see if that fixes it?

**Comment by thirsch** [comment]
It's ok, that your friendsofsymfony1/symfony1/lib/vendor/swiftmailer is empty, as the dependency will be installed by composer next to friendsofsymfony1/symfony1 as swiftmailer/swiftmailer as mentalstring already said. Both should appear in [project_root]/lib/vendor.

**Comment by flmommens** [comment]
This is working now, thanks!

**Comment by flmommens** [comment]
Actually, no, it's working with a specific older version of 5.4.12. With the 6.3.0 that's installed by default, I get an error about the Class Swift being defined twice.

**Comment by thePanz** [comment]
Closing as fixed! :)
