### ISSUE TITLE
Adding swiftmailer to fos1 group to apply some php 8.2 patches to the code?

### ISSUE THREAD

**Issue by thirsch** [FriendsOfSymfony1/symfony1#319]
We've created a fork and made some adjustments to the latest swiftmailer version to be compatible with PHP 8.2. Should we create an official fork here in the fos1 group and apply the patches there? For reference: https://github.com/vemaeg/swiftmailer/commit/d46f73f35cfdcd67b1009e800a2691bfa9cacc49

I thought I asked that already somewhere, but wasn't able to find it, therefore I'm opening an issue for it.

**Comment by alquerci** [comment]
FYI: From #302 I rise error level until deprecation.
_Aside, I am waiting for that PR to be merged to add more constraints on PHP error_reporting._

And I got the one deprecation mention on the patch.

> Deprecated: Callables of the form ["Swift_NullTransport",            
  "Swift_Transport_NullTransport::__construct"] are deprecated         
  (in lib/vendor/swiftmailer/lib/classes/Swift/NullTransport.php on    
  line 21)

IMHO deprecation should be ignored as it ask us too much work.

```
error_reporting:        <?php echo ((E_ALL | E_STRICT) ^ E_USER_DEPRECATED ^ E_DEPRECATED)."\n" ?>
```

**OR**

It's an opportunity to test the idea to use current Symfony component with `symfony/mailer`.
Without any BC breaks.

It will be a good experiment.

**Comment by connorhu** [comment]
In framework/library development the only acceptable error_reporting level is E_ALL. IMHO.

**Comment by alquerci** [comment]
@connorhu I agree we need to be strict.

I talked on framework/library user point of view.

sf1 use swiftmailer.

**Comment by mentalstring** [comment]
Given that swiftmailer is a requirement of symfony1, I agree that it would sensible if we could have a fork under fos1 where just the minimum necessary changes for PHP compatibility could be done.

**Comment by connorhu** [comment]
@thePanz Please create the new repo and invite @thirsch at least.

**Comment by thePanz** [comment]
@connorhu done: https://github.com/FriendsOfSymfony1/swiftmailer

Please let's move there for further discussions :)

**Comment by connorhu** [comment]
Thank you!
