### ISSUE TITLE
sfAPCCache seems to not be compatible with apcu

### ISSUE THREAD

**Issue by j0k3r** [FriendsOfSymfony1/symfony1#48]
APCu seems to not use the same way to store "key".
sfAPCCache->getCacheInfo():

``` php
  protected function getCacheInfo($key)
  {
    if (!$this->enabled)
    {
      return false;
    }

    $infos = apc_cache_info('user');

    if (is_array($infos['cache_list']))
    {
      foreach ($infos['cache_list'] as $info)
      {
        if ($this->getOption('prefix').$key == $info['info'])
        {
          return $info;
        }
      }
    }

    return null;
  }
```

Before this if `if ($this->getOption('prefix').$key == $info['info'])`, I vardumped the `$info` array and here it is for APCu & APC.
With APCu:

```
array (size=9)
  'key' => string 'account:/localhost/all/main/index/__sf_cache_key/item_tags_8267' (length=63)
  'ttl' => int 86400
  'nhits' => float 0
  'mtime' => int 1394384708
  'ctime' => int 1394384708
  'dtime' => int 0
  'atime' => int 1394384708
  'ref_count' => int 0
  'mem_size' => int 1712
```

And this with APC:

```
array (size=9)
  'info' => string 'account:/localhost/all/main/index/__sf_cache_key/item_tags_8267' (length=63)
  'ttl' => int 86400
  'nhits' => float 0
  'mtime' => int 1394384708
  'ctime' => int 1394384708
  'dtime' => int 0
  'atime' => int 1394384708
  'ref_count' => int 0
  'mem_size' => int 1712
```

Spot the first key from the array ? info != key
Should we create a `sfAPCuCache` ? The problem will also appear in `removePattern()`.

**Comment by mentalstring** [comment]
I have been using APCu in production without any issue with sfAPCCache

I believe APCu 4.0.7 [has fixed this](https://pecl.php.net/package-changelog.php?package=APCu&release=4.0.7) and with it, the API is the same as APC. Unless I'm missing something, this fix only makes it compatible with older versions of APCu.
